### ISSUE TITLE
User guides and documentation improvements

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#761]
# Tasks
- [x] Core Concepts user guide https://hera.readthedocs.io/en/latest/user-guides/core-concepts/
- [x] Script annotations as a new user guide and link from [advanced section](https://hera.readthedocs.io/en/latest/getting-started/walk-through/advanced-hera-features/#script-annotations) (it's a bit long and deserves its own page)
- [x] Runner user guide
- [x] Pydantic support user guide/walkthrough section
- [x] Exit handlers are deprecated, we should rewrite/replace https://hera.readthedocs.io/en/latest/getting-started/walk-through/advanced-workflow-features/#exit-handlers with hooks - https://argoproj.github.io/argo-workflows/lifecyclehook/

**Comment by elliotgunton** [comment]
Added a small pydantic section, will rewrite when upgrading to Pydantic V2 when addressing #713
