### ISSUE TITLE
Hera's Artifact class is missing `optional`

### ISSUE THREAD

**Issue by elliotgunton** [argoproj-labs/hera#814]
<h2>Pre-bug-report checklist</h2>

**1. This bug can be reproduced using YAML**
- [ ] Yes [👉 Please report a bug to the Argo Workflows GitHub 👈](https://github.com/argoproj/argo-workflows/issues/new/choose)
- [x] No

**2. This bug occurs when...**
- [x] running Hera code without submitting to Argo (e.g. when exporting to YAML)
- [ ] running Hera code and submitting to Argo

<h2>Bug report</h2>

**Describe the bug**
This example is not possible to rewrite with Hera classes due to Artifact missing the `optional` field:
https://github.com/argoproj/argo-workflows/blob/08096fc0512ed57a89e4a95ced56512631d8c94b/examples/ci-workflowtemplate.yaml#L99

Labelling as enhancement but easier to report as a bug

## Tasks
- [x] Add `optional` to Artifact
- [x] Add ci-workflowtemplate example
